### ISSUE TITLE
Use of data-files setting in Cabal is not obvious.

### ISSUE THREAD

**Issue by seanparsons** [tibbe/ekg#48] opened 2015-08-18 10:38 UTC
The files stipulated in the data-files setting are "installed" in the Cabal sense, but this means they're outside the built executable that will include the ekg library. As a result this means those files have to be carried around with the binary and the "ekg_datadir" environment variable set appropriately.

From my perspective it would be easier if they were included using the file-embed library, but at the very least this needs mentioning in the README as it's totally opaque until you dig through the ekg code and .cabal file.

**Comment by seanparsons** [comment] 2015-08-18 10:47
In fact if it's not on an image that was normally installed to it's quite hard to get the appropriate folder to take these files from, making a very brittle build process as a result.

**Comment by tibbe** [comment] 2015-08-18 19:37
Duplicate of #13.

**Closed by tibbe** 2015-08-18 19:37 UTC

**Comment by seanparsons** [comment] 2015-08-18 21:23
@tibbe While this is a duplicate, that story has been closed for 2 years and it's still a problem, if you want to avoid TH can we do something crazy like embed what the TH code would've generated?

**Comment by cgag** [comment] 2015-11-23 07:32
Agreed with this being a problem.  I eventually found the assets dir in ~/.stack/snapshots/x86_64-linux/nightly-2015-11-19/7.10.2/share/x86_64-linux-ghc-7.10.2/ekg-0.4.0.8/assets.

Everything worked once I copied that into my project dir and ran it with ekg_datadir set to my  project dir.  I'm going to look into adding a warning when it can't find the data dir as suggest in https://github.com/tibbe/ekg/pull/13.

**Comment by ods94065** [comment] 2016-02-27 15:52
Yup, this bit me. When I install ekg as a dependency of my web app using Stack/Docker, I end up with the following directory:

`/Users/owen/.stack/snapshots/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-5.4/7.10.3/share/x86_64-linux-ghc-7.10.3/ekg-0.4.0.9/assets`

Maybe I could create a build script that looked for `~/\.stack/snapshots/.+/ekg-[^/]+/assets` and copied them somewhere where the Docker build could get a hold of them (I'm building my web app to run in a Docker container), but I decided to just cheat. I'm pinning the `ekg` version for now and copying the assets directory into my project.
